### ISSUE TITLE
Non editable field type to display a value

### ISSUE THREAD

**Issue by christophepersoz** [neu-rah/ArduinoMenu#116]
Hi Rui,

Is there a way to display a value inside the menu, which is non editable, and which display a value that can be the result of a calculation for example ?

Thanks

**Comment by neu-rah** [comment]
yes, make it read only, it will still update

**Comment by christophepersoz** [comment]
Oh great! I thought that disable will hide it from the menu. Perfect! Thanks a lot

**Comment by christophepersoz** [comment]
Sorry, how do you determine the index value to hide it ?

**Comment by neu-rah** [comment]
its zero indexed and static, so no chance of changing
[0] is the first option

the syntax is "alice in wonderland" inspired.. :D have a note to improve it.

**Comment by christophepersoz** [comment]
OK, lets go for the trial and error experiments ! ;)

**Comment by neu-rah** [comment]
why, you don't know your menus?
its zero indexed for each menu, and all menus have names so...

mainMenu[1];//its main menu's second option
subMenuX[3];//is subMenuX forth option

**Comment by christophepersoz** [comment]
Oh, so if I have a structure like this, 

```
MENU(hwdSMENU, ">HARDWARE", doNothing, noEvent, noStyle,
    SUBMENU( _mDISP ),
    SUBMENU( _mWRAP ),
    SUBMENU( _mLEDS ),
    FIELD( _LEDW, "LED COLS ", "", _MINLEDW, _MAXLEDW, 1, 0, _updPOWERDRAW, noEvent, wrapStyle ),
    FIELD( _LEDH, "LED ROWS ", "", _MINLEDH, _MAXLEDH, 1, 0, _updPOWERDRAW, noEvent, wrapStyle ),
    FIELD( POWERDRAW, "POWER DRAW ", "mA", 0, _MAXPOWERDRAW, 0, 0, _updPOWERDRAW, noEvent, wrapStyle ),
    EXIT( "< BACK" )
    );
```

I guess that POWERDRAW is hwdSMENU[5] // fifth option of the submenu hwdSMENU.

I thought that I had to count from mainMENU ^^

**Comment by neu-rah** [comment]
exact, zero indexed for each menu
plus on your code you now have a hwdSMENU variable that is of type: 

menu - https://github.com/neu-rah/ArduinoMenu/blob/master/src/menu.h#L206
menuNode - https://github.com/neu-rah/ArduinoMenu/blob/master/src/menu.h#L193
navtarget - https://github.com/neu-rah/ArduinoMenu/blob/master/src/menu.h#L101
prompt - https://github.com/neu-rah/ArduinoMenu/blob/master/src/menu.h#L55

inheriting all those method and data from the above hierarchy, the data is not very interesting because its only a shadow pointer to somewhere on flash

by indexing on it you have a prompt object
https://github.com/neu-rah/ArduinoMenu/blob/master/src/menu.h#L197

and if you know the type you can cast it to the correct type and have more usefull info, ie:
((menuField*)&hwdSMENU[3])->... //this gives you the forth field object, and you can access its members or call methods

**Comment by christophepersoz** [comment]
Awesome! That's quite a lot of changes since the v2

**Comment by neu-rah** [comment]
And look there are are enable/disable method for prompts :D
Sometimes I get surprised too

**Comment by neu-rah** [comment]
Guess I have to highlight those things on wiki

**Comment by christophepersoz** [comment]
Good idea!
